import { Currency } from "@/types";

export const currencies: Currency[] = [
  { name: "AED", symbol: "د.إ", countryCode: "ae", emoji: "🇦🇪", fullName: "United Arab Emirates Dirham" },
  { name: "AFN", symbol: "؋", countryCode: "af", emoji: "🇦🇫", fullName: "Afghan Afghani" },
  { name: "ALL", symbol: "L", countryCode: "al", emoji: "🇦🇱", fullName: "Albanian Lek" },
  { name: "AMD", symbol: "֏", countryCode: "am", emoji: "🇦🇲", fullName: "Armenian Dram" },
  { name: "ANG", symbol: "ƒ", countryCode: "cw", emoji: "🇨🇼", fullName: "Netherlands Antillean Guilder" },
  { name: "AOA", symbol: "Kz", countryCode: "ao", emoji: "🇦🇴", fullName: "Angolan Kwanza" },
  { name: "ARS", symbol: "$", countryCode: "ar", emoji: "🇦🇷", fullName: "Argentine Peso" },
  { name: "AUD", symbol: "$", countryCode: "au", emoji: "🇦🇺", fullName: "Australian Dollar" },
  { name: "AWG", symbol: "ƒ", countryCode: "aw", emoji: "🇦🇼", fullName: "Aruban Florin" },
  { name: "AZN", symbol: "₼", countryCode: "az", emoji: "🇦🇿", fullName: "Azerbaijani Manat" },
  { name: "BAM", symbol: "KM", countryCode: "ba", emoji: "🇧🇦", fullName: "Bosnia and Herzegovina Convertible Mark" },
  { name: "BBD", symbol: "$", countryCode: "bb", emoji: "🇧🇧", fullName: "Barbadian Dollar" },
  { name: "BDT", symbol: "৳", countryCode: "bd", emoji: "🇧🇩", fullName: "Bangladeshi Taka" },
  { name: "BGN", symbol: "лв", countryCode: "bg", emoji: "🇧🇬", fullName: "Bulgarian Lev" },
  { name: "BHD", symbol: ".د.ب", countryCode: "bh", emoji: "🇧🇭", fullName: "Bahraini Dinar" },
  { name: "BIF", symbol: "FBu", countryCode: "bi", emoji: "🇧🇮", fullName: "Burundian Franc" },
  { name: "BMD", symbol: "$", countryCode: "bm", emoji: "🇧🇲", fullName: "Bermudian Dollar" },
  { name: "BND", symbol: "$", countryCode: "bn", emoji: "🇧🇳", fullName: "Brunei Dollar" },
  { name: "BOB", symbol: "Bs.", countryCode: "bo", emoji: "🇧🇴", fullName: "Bolivian Boliviano" },
  { name: "BRL", symbol: "R$", countryCode: "br", emoji: "🇧🇷", fullName: "Brazilian Real" },
  { name: "BSD", symbol: "$", countryCode: "bs", emoji: "🇧🇸", fullName: "Bahamian Dollar" },
  { name: "BTN", symbol: "Nu.", countryCode: "bt", emoji: "🇧🇹", fullName: "Bhutanese Ngultrum" },
  { name: "BWP", symbol: "P", countryCode: "bw", emoji: "🇧🇼", fullName: "Botswana Pula" },
  { name: "BYN", symbol: "Br", countryCode: "by", emoji: "🇧🇾", fullName: "Belarusian Ruble" },
  { name: "BZD", symbol: "$", countryCode: "bz", emoji: "🇧🇿", fullName: "Belize Dollar" },
  { name: "CAD", symbol: "$", countryCode: "ca", emoji: "🇨🇦", fullName: "Canadian Dollar" },
  { name: "CDF", symbol: "FC", countryCode: "cd", emoji: "🇨🇩", fullName: "Congolese Franc" },
  { name: "CHF", symbol: "CHF", countryCode: "ch", emoji: "🇨🇭", fullName: "Swiss Franc" },
  { name: "CLP", symbol: "$", countryCode: "cl", emoji: "🇨🇱", fullName: "Chilean Peso" },
  { name: "CNY", symbol: "¥", countryCode: "cn", emoji: "🇨🇳", fullName: "Chinese Yuan" },
  { name: "COP", symbol: "$", countryCode: "co", emoji: "🇨🇴", fullName: "Colombian Peso" },
  { name: "CRC", symbol: "₡", countryCode: "cr", emoji: "🇨🇷", fullName: "Costa Rican Colón" },
  { name: "CUP", symbol: "$", countryCode: "cu", emoji: "🇨🇺", fullName: "Cuban Peso" },
  { name: "CVE", symbol: "$", countryCode: "cv", emoji: "🇨🇻", fullName: "Cape Verdean Escudo" },
  { name: "CZK", symbol: "Kč", countryCode: "cz", emoji: "🇨🇿", fullName: "Czech Koruna" },
  { name: "DJF", symbol: "Fdj", countryCode: "dj", emoji: "🇩🇯", fullName: "Djiboutian Franc" },
  { name: "DKK", symbol: "kr", countryCode: "dk", emoji: "🇩🇰", fullName: "Danish Krone" },
  { name: "DOP", symbol: "$", countryCode: "do", emoji: "🇩🇴", fullName: "Dominican Peso" },
  { name: "DZD", symbol: "د.ج", countryCode: "dz", emoji: "🇩🇿", fullName: "Algerian Dinar" },
  { name: "EGP", symbol: "£", countryCode: "eg", emoji: "🇪🇬", fullName: "Egyptian Pound" },
  { name: "ERN", symbol: "Nfk", countryCode: "er", emoji: "🇪🇷", fullName: "Eritrean Nakfa" },
  { name: "ETB", symbol: "Br", countryCode: "et", emoji: "🇪🇹", fullName: "Ethiopian Birr" },
  { name: "EUR", symbol: "€", countryCode: "eu", emoji: "🇪🇺", fullName: "Euro" },
  { name: "FJD", symbol: "$", countryCode: "fj", emoji: "🇫🇯", fullName: "Fijian Dollar" },
  { name: "FKP", symbol: "£", countryCode: "fk", emoji: "🇫🇰", fullName: "Falkland Islands Pound" },
  { name: "FOK", symbol: "kr", countryCode: "fo", emoji: "🇫🇴", fullName: "Faroese Króna" },
  { name: "GBP", symbol: "£", countryCode: "gb", emoji: "🇬🇧", fullName: "British Pound Sterling" },
  { name: "GEL", symbol: "₾", countryCode: "ge", emoji: "🇬🇪", fullName: "Georgian Lari" },
  { name: "GGP", symbol: "£", countryCode: "gg", emoji: "🇬🇬", fullName: "Guernsey Pound" },
  { name: "GHS", symbol: "₵", countryCode: "gh", emoji: "🇬🇭", fullName: "Ghanaian Cedi" },
  { name: "GIP", symbol: "£", countryCode: "gi", emoji: "🇬🇮", fullName: "Gibraltar Pound" },
  { name: "GMD", symbol: "D", countryCode: "gm", emoji: "🇬🇲", fullName: "Gambian Dalasi" },
  { name: "GNF", symbol: "FG", countryCode: "gn", emoji: "🇬🇳", fullName: "Guinean Franc" },
  { name: "GTQ", symbol: "Q", countryCode: "gt", emoji: "🇬🇹", fullName: "Guatemalan Quetzal" },
  { name: "GYD", symbol: "$", countryCode: "gy", emoji: "🇬🇾", fullName: "Guyanese Dollar" },
  { name: "HKD", symbol: "$", countryCode: "hk", emoji: "🇭🇰", fullName: "Hong Kong Dollar" },
  { name: "HNL", symbol: "L", countryCode: "hn", emoji: "🇭🇳", fullName: "Honduran Lempira" },
  { name: "HRK", symbol: "kn", countryCode: "hr", emoji: "🇭🇷", fullName: "Croatian Kuna" },
  { name: "HTG", symbol: "G", countryCode: "ht", emoji: "🇭🇹", fullName: "Haitian Gourde" },
  { name: "HUF", symbol: "Ft", countryCode: "hu", emoji: "🇭🇺", fullName: "Hungarian Forint" },
  { name: "IDR", symbol: "Rp", countryCode: "id", emoji: "🇮🇩", fullName: "Indonesian Rupiah" },
  { name: "ILS", symbol: "₪", countryCode: "il", emoji: "🇮🇱", fullName: "Israeli New Shekel" },
  { name: "IMP", symbol: "£", countryCode: "im", emoji: "🇮🇲", fullName: "Isle of Man Pound" },
  { name: "INR", symbol: "₹", countryCode: "in", emoji: "🇮🇳", fullName: "Indian Rupee" },
  { name: "IQD", symbol: "ع.د", countryCode: "iq", emoji: "🇮🇶", fullName: "Iraqi Dinar" },
  { name: "IRR", symbol: "﷼", countryCode: "ir", emoji: "🇮🇷", fullName: "Iranian Rial" },
  { name: "ISK", symbol: "kr", countryCode: "is", emoji: "🇮🇸", fullName: "Icelandic Króna" },
  { name: "JEP", symbol: "£", countryCode: "je", emoji: "🇯🇪", fullName: "Jersey Pound" },
  { name: "JMD", symbol: "$", countryCode: "jm", emoji: "🇯🇲", fullName: "Jamaican Dollar" },
  { name: "JOD", symbol: "د.ا", countryCode: "jo", emoji: "🇯🇴", fullName: "Jordanian Dinar" },
  { name: "JPY", symbol: "¥", countryCode: "jp", emoji: "🇯🇵", fullName: "Japanese Yen" },
  { name: "KES", symbol: "KSh", countryCode: "ke", emoji: "🇰🇪", fullName: "Kenyan Shilling" },
  { name: "KGS", symbol: "с", countryCode: "kg", emoji: "🇰🇬", fullName: "Kyrgyzstani Som" },
  { name: "KHR", symbol: "៛", countryCode: "kh", emoji: "🇰🇭", fullName: "Cambodian Riel" },
  { name: "KID", symbol: "$", countryCode: "ki", emoji: "🇰🇮", fullName: "Kiribati Dollar" },
  { name: "KMF", symbol: "CF", countryCode: "km", emoji: "🇰🇲", fullName: "Comorian Franc" },
  { name: "KRW", symbol: "₩", countryCode: "kr", emoji: "🇰🇷", fullName: "South Korean Won" },
  { name: "KWD", symbol: "د.ك", countryCode: "kw", emoji: "🇰🇼", fullName: "Kuwaiti Dinar" },
  { name: "KYD", symbol: "$", countryCode: "ky", emoji: "🇰🇾", fullName: "Cayman Islands Dollar" },
  { name: "KZT", symbol: "₸", countryCode: "kz", emoji: "🇰🇿", fullName: "Kazakhstani Tenge" },
  { name: "LAK", symbol: "₭", countryCode: "la", emoji: "🇱🇦", fullName: "Lao Kip" },
  { name: "LBP", symbol: "ل.ل", countryCode: "lb", emoji: "🇱🇧", fullName: "Lebanese Pound" },
  { name: "LKR", symbol: "Rs", countryCode: "lk", emoji: "🇱🇰", fullName: "Sri Lankan Rupee" },
  { name: "LRD", symbol: "$", countryCode: "lr", emoji: "🇱🇷", fullName: "Liberian Dollar" },
  { name: "LSL", symbol: "L", countryCode: "ls", emoji: "🇱🇸", fullName: "Lesotho Loti" },
  { name: "LYD", symbol: "ل.د", countryCode: "ly", emoji: "🇱🇾", fullName: "Libyan Dinar" },
  { name: "MAD", symbol: "د.م.", countryCode: "ma", emoji: "🇲🇦", fullName: "Moroccan Dirham" },
  { name: "MDL", symbol: "L", countryCode: "md", emoji: "🇲🇩", fullName: "Moldovan Leu" },
  { name: "MGA", symbol: "Ar", countryCode: "mg", emoji: "🇲🇬", fullName: "Malagasy Ariary" },
  { name: "MKD", symbol: "ден", countryCode: "mk", emoji: "🇲🇰", fullName: "Macedonian Denar" },
  { name: "MMK", symbol: "K", countryCode: "mm", emoji: "🇲🇲", fullName: "Myanmar Kyat" },
  { name: "MNT", symbol: "₮", countryCode: "mn", emoji: "🇲🇳", fullName: "Mongolian Tugrik" },
  { name: "MOP", symbol: "P", countryCode: "mo", emoji: "🇲🇴", fullName: "Macanese Pataca" },
  { name: "MRU", symbol: "UM", countryCode: "mr", emoji: "🇲🇷", fullName: "Mauritanian Ouguiya" },
  { name: "MUR", symbol: "₨", countryCode: "mu", emoji: "🇲🇺", fullName: "Mauritian Rupee" },
  { name: "MVR", symbol: ".ރ", countryCode: "mv", emoji: "🇲🇻", fullName: "Maldivian Rufiyaa" },
  { name: "MWK", symbol: "MK", countryCode: "mw", emoji: "🇲🇼", fullName: "Malawian Kwacha" },
  { name: "MXN", symbol: "$", countryCode: "mx", emoji: "🇲🇽", fullName: "Mexican Peso" },
  { name: "MYR", symbol: "RM", countryCode: "my", emoji: "🇲🇾", fullName: "Malaysian Ringgit" },
  { name: "MZN", symbol: "MT", countryCode: "mz", emoji: "🇲🇿", fullName: "Mozambican Metical" },
  { name: "NAD", symbol: "$", countryCode: "na", emoji: "🇳🇦", fullName: "Namibian Dollar" },
  { name: "NGN", symbol: "₦", countryCode: "ng", emoji: "🇳🇬", fullName: "Nigerian Naira" },
  { name: "NIO", symbol: "C$", countryCode: "ni", emoji: "🇳🇮", fullName: "Nicaraguan Córdoba" },
  { name: "NOK", symbol: "kr", countryCode: "no", emoji: "🇳🇴", fullName: "Norwegian Krone" },
  { name: "NPR", symbol: "₨", countryCode: "np", emoji: "🇳🇵", fullName: "Nepalese Rupee" },
  { name: "NZD", symbol: "$", countryCode: "nz", emoji: "🇳🇿", fullName: "New Zealand Dollar" },
  { name: "OMR", symbol: "ر.ع.", countryCode: "om", emoji: "🇴🇲", fullName: "Omani Rial" },
  { name: "PAB", symbol: "B/.", countryCode: "pa", emoji: "🇵🇦", fullName: "Panamanian Balboa" },
  { name: "PEN", symbol: "S/.", countryCode: "pe", emoji: "🇵🇪", fullName: "Peruvian Sol" },
  { name: "PGK", symbol: "K", countryCode: "pg", emoji: "🇵🇬", fullName: "Papua New Guinean Kina" },
  { name: "PHP", symbol: "₱", countryCode: "ph", emoji: "🇵🇭", fullName: "Philippine Peso" },
  { name: "PKR", symbol: "₨", countryCode: "pk", emoji: "🇵🇰", fullName: "Pakistani Rupee" },
  { name: "PLN", symbol: "zł", countryCode: "pl", emoji: "🇵🇱", fullName: "Polish Złoty" },
  { name: "PYG", symbol: "₲", countryCode: "py", emoji: "🇵🇾", fullName: "Paraguayan Guaraní" },
  { name: "QAR", symbol: "ر.ق", countryCode: "qa", emoji: "🇶🇦", fullName: "Qatari Rial" },
  { name: "RON", symbol: "lei", countryCode: "ro", emoji: "🇷🇴", fullName: "Romanian Leu" },
  { name: "RSD", symbol: "дин", countryCode: "rs", emoji: "🇷🇸", fullName: "Serbian Dinar" },
  { name: "RUB", symbol: "₽", countryCode: "ru", emoji: "🇷🇺", fullName: "Russian Ruble" },
  { name: "RWF", symbol: "RF", countryCode: "rw", emoji: "🇷🇼", fullName: "Rwandan Franc" },
  { name: "SAR", symbol: "ر.س", countryCode: "sa", emoji: "🇸🇦", fullName: "Saudi Riyal" },
  { name: "SBD", symbol: "$", countryCode: "sb", emoji: "🇸🇧", fullName: "Solomon Islands Dollar" },
  { name: "SCR", symbol: "₨", countryCode: "sc", emoji: "🇸🇨", fullName: "Seychellois Rupee" },
  { name: "SDG", symbol: "ج.س.", countryCode: "sd", emoji: "🇸🇩", fullName: "Sudanese Pound" },
  { name: "SEK", symbol: "kr", countryCode: "se", emoji: "🇸🇪", fullName: "Swedish Krona" },
  { name: "SGD", symbol: "$", countryCode: "sg", emoji: "🇸🇬", fullName: "Singapore Dollar" },
  { name: "SHP", symbol: "£", countryCode: "sh", emoji: "🇸🇭", fullName: "Saint Helena Pound" },
  { name: "SLE", symbol: "Le", countryCode: "sl", emoji: "🇸🇱", fullName: "Sierra Leonean Leone" },
  { name: "SLL", symbol: "Le", countryCode: "sll", emoji: "🇸🇱", fullName: "Sierra Leonean Leone" },
  { name: "SOS", symbol: "S", countryCode: "so", emoji: "🇸🇴", fullName: "Somali Shilling" },
  { name: "SRD", symbol: "$", countryCode: "sr", emoji: "🇸🇷", fullName: "Surinamese Dollar" },
  { name: "SSP", symbol: "£", countryCode: "ss", emoji: "🇸🇸", fullName: "South Sudanese Pound" },
  { name: "STN", symbol: "Db", countryCode: "st", emoji: "🇸🇹", fullName: "Sao Tome and Principe Dobra" },
  { name: "SYP", symbol: "£", countryCode: "sy", emoji: "🇸🇾", fullName: "Syrian Pound" },
  { name: "SZL", symbol: "L", countryCode: "sz", emoji: "🇱🇸", fullName: "Eswatini Lilangeni" },
  { name: "THB", symbol: "฿", countryCode: "th", emoji: "🇹🇭", fullName: "Thai Baht" },
  { name: "TJS", symbol: "ЅМ", countryCode: "tj", emoji: "🇹🇯", fullName: "Tajikistani Somoni" },
  { name: "TMT", symbol: "m", countryCode: "tm", emoji: "🇹🇲", fullName: "Turkmenistani Manat" },
  { name: "TND", symbol: "د.ت", countryCode: "tn", emoji: "🇹🇳", fullName: "Tunisian Dinar" },
  { name: "TOP", symbol: "T$", countryCode: "to", emoji: "🇹🇴", fullName: "Tongan Paʻanga" },
  { name: "TRY", symbol: "₺", countryCode: "tr", emoji: "🇹🇷", fullName: "Turkish Lira" },
  { name: "TTD", symbol: "$", countryCode: "tt", emoji: "🇹🇹", fullName: "Trinidad and Tobago Dollar" },
  { name: "TVD", symbol: "$", countryCode: "tv", emoji: "🇹🇻", fullName: "Tuvaluan Dollar" },
  { name: "TWD", symbol: "$", countryCode: "tw", emoji: "🇹🇼", fullName: "New Taiwan Dollar" },
  { name: "TZS", symbol: "Sh", countryCode: "tz", emoji: "🇹🇿", fullName: "Tanzanian Shilling" },
  { name: "UAH", symbol: "₴", countryCode: "ua", emoji: "🇺🇦", fullName: "Ukrainian Hryvnia" },
  { name: "UGX", symbol: "USh", countryCode: "ug", emoji: "🇺🇬", fullName: "Ugandan Shilling" },
  { name: "USD", symbol: "$", countryCode: "us", emoji: "🇺🇸", fullName: "United States Dollar" },
  { name: "UYU", symbol: "$", countryCode: "uy", emoji: "🇺🇾", fullName: "Uruguayan Peso" },
  { name: "UZS", symbol: "so'm", countryCode: "uz", emoji: "🇺🇿", fullName: "Uzbekistani So'm" },
  { name: "VES", symbol: "Bs.", countryCode: "ve", emoji: "🇻🇪", fullName: "Venezuelan Bolívar (Soberano)" },
  { name: "VND", symbol: "₫", countryCode: "vn", emoji: "🇻🇳", fullName: "Vietnamese đồng" },
  { name: "VUV", symbol: "VT", countryCode: "vu", emoji: "🇻🇺", fullName: "Vanuatu Vatu" },
  { name: "WST", symbol: "T", countryCode: "ws", emoji: "🇼🇸", fullName: "Samoan Tālā" },
  { name: "YER", symbol: "﷼", countryCode: "ye", emoji: "🇾🇪", fullName: "Yemeni Rial" },
  { name: "ZAR", symbol: "R", countryCode: "za", emoji: "🇿🇦", fullName: "South African Rand" },
  { name: "ZMW", symbol: "ZK", countryCode: "zm", emoji: "🇿🇲", fullName: "Zambian Kwacha" },
  { name: "ZWL", symbol: "$", countryCode: "zw", emoji: "🇿🇼", fullName: "Zimbabwean Dollar" },
  // Add more currencies as needed
];
